### ISSUE TITLE
Error persisting lists of maps

### ISSUE THREAD

**Issue by frepond** [inaka/sumo_db_riak#29]
In sumo_store_riak:506 it's using sumo_utils:to_bin/1 which does not support maps. This lead to an error trying to persist a list of maps since maps are not converted to binary before being added to a riak set.

**Comment by ferigis** [comment]
hi @frepond , thanks for using sumo!!
I think you missed to define your schema correctly. If you are going to use list types it is a `custom` Riak's type. For this reason you must to declare that field as a `custom` of type `list`.

```erlang
sumo:new_field(attributes, custom, [{type, list}])
```
I have added a simple test with `users` where I used list types.

Thanks

**Comment by frepond** [comment]
Hi @ferigis,

I've defined 

```erlang
sumo:new_field(emails,        custom, [{type, list}]),
```

The problem is when emails are maps.

**Comment by frepond** [comment]
Sorry, using {type, list} it's working but persisted as base64 encoded binary not a crdt set.

**Comment by ferigis** [comment]
Hi @frepond , take a look on the example I pushed this morning.
see on https://github.com/inaka/sumo_db_riak/blob/master/test/users_SUITE.erl#L36 I am storing a list of maps and retrieving it correctly.
If the schema is well defined it doesn't execute the `to_bin/1` function

**Comment by ferigis** [comment]
Hi @frepond , take a look on the example I pushed this morning.
see on https://github.com/inaka/sumo_db_riak/blob/master/test/users_SUITE.erl#L36 I am storing a list of maps and retrieving it correctly.
If the schema is well defined it doesn't execute the `to_bin/1` function

**Comment by ferigis** [comment]
@frepond we can talk about it [here](inaka.net/hipchat)

**Comment by frepond** [comment]
@ferigis hipchat link takes me to 404 page

**Comment by ferigis** [comment]
sorry, wrong url...
try [here](http://inaka.net/hipchat)

**Comment by frepond** [comment]
@ferigis sorry, but I couldn't find how to contact you at hipchat. It would be nice to discuss this issue with you.
